### ISSUE TITLE
Discord embed command returning "undefined" errors

### ISSUE THREAD

**Issue by missgorl** [Avert-Development/avert#1]
I suspect that there is an error with the result fetch, as the variables defined by it are undefined. This initially happened only with some URLs but is happening on all URLs at this point. 

Error from debug console:

```
(node:8756) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'urlscan' of undefined
    at embed (c:\Users\isaac\OneDrive\Documents\Avert\avert\index.js:64:90)
    at `c:\Users\isaac\OneDrive\Documents\Avert\avert\index.js:99:120`
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by missgorl** [comment]
Issue was due to a mistake in defining the APIKEY environmental variable
